## Function Description
You’re optimising a cake recipe using a black-box function with five ingredient inputs, for example flour, sugar, eggs, butter and milk. Each recipe is evaluated with a combined score based on flavour, consistency, calories, waste and cost, where each factor contributes negative points as judged by an expert taster. This means the total score is negative by design and the goal is to bring the score as close to zero as possible i.e. maximuse the negative of the total sum. 


## Load and Prepare Data

In [1]:
import numpy as np
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import Matern, WhiteKernel, ConstantKernel
from scipy.stats.qmc import Sobol
from scipy.stats import norm
import warnings
from sklearn.exceptions import ConvergenceWarning

warnings.filterwarnings(
    "ignore",
    category=ConvergenceWarning,
    module="sklearn"
)

# Load original dataset
X = np.load("../data/function_6/initial_inputs.npy")
y = np.load("../data/function_6/initial_outputs.npy")
d = X.shape[1] # dimension

print(f"original n: {len(X)}")
print()

# week 1 = initial

# week 2
x_new = np.array([[0.444424, 0.277423, 0.760053, 0.992452, 0.038232]])
y_new = np.array([-0.45856193410139306])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 3
x_new = np.array([[0.455338, 0.062714, 0.630801, 0.998447, 0.018519]])
y_new = np.array([-0.6798942792249156])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 4
x_new = np.array([[0.507231, 0.359107, 0.956651, 0.942272, 0.013719]])
y_new = np.array([-0.6288399244899063])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# Week 5
x_new = np.array([[0.449204, 0.396971, 0.404311, 0.984358, 0.015693]])
y_new = np.array([-0.572157138868939])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 6
x_new = np.array([[0.478491, 0.351883, 0.619499, 0.829965, 0.020048]])
y_new = np.array([-0.23851334784253364])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 7
x_new = np.array([[0.428561, 0.273493, 0.610623, 0.645116, 0.002955]])
y_new = np.array([-0.3226277584878637])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 8
x_new = np.array([[0.460926, 0.360586, 0.617558, 0.696377, 0.002409]])
y_new = np.array([-0.30722256011214166])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 9
x_new = np.array([[0.458929, 0.357106, 0.732553, 0.757329, 0.005824]])
y_new = np.array([-0.19454663638677158])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 10
x_new = np.array([[0.427534, 0.390196, 0.697130, 0.724388, 0.007622]])
y_new = np.array([-0.17897198508021397])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 11
x_new = np.array([[0.326533, 0.391750, 0.698954, 0.774100, 0.003347]])
y_new = np.array([-0.24177542505235383])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 12
x_new = np.array([[0.409174, 0.316481, 0.673069, 0.767438, 0.006704]])
y_new = np.array([-0.11109794756770958])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 13
x_new = np.array([[0.327873, 0.205283, 0.874017, 0.715164, 0.003340]])
y_new = np.array([-0.6238608089880437])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# final submission
x_new = np.array([[0.397635, 0.367236, 0.627289, 0.833291, 0.011553]])
y_new = np.array([-0.21540785034195753])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

print("X:\n", X)
print()
print("y:\n", y)
print()
print("n: ", len(y))
print()
idx_best = np.argmax(y)
print(f"current maximum:\nn: {idx_best+1}\ny: {y[idx_best]}\nX: {X[idx_best]}")

original n: 20

X:
 [[0.7281861  0.15469257 0.73255167 0.69399651 0.05640131]
 [0.24238435 0.84409997 0.5778091  0.67902128 0.50195289]
 [0.72952261 0.7481062  0.67977464 0.35655228 0.67105368]
 [0.77062024 0.11440374 0.04677993 0.64832428 0.27354905]
 [0.6188123  0.33180214 0.18728787 0.75623847 0.3288348 ]
 [0.78495809 0.91068235 0.7081201  0.95922543 0.0049115 ]
 [0.14511079 0.8966846  0.89632223 0.72627154 0.23627199]
 [0.94506907 0.28845905 0.97880576 0.96165559 0.59801594]
 [0.12572016 0.86272469 0.02854433 0.24660527 0.75120624]
 [0.75759436 0.35583141 0.0165229  0.4342072  0.11243304]
 [0.5367969  0.30878091 0.41187929 0.38822518 0.5225283 ]
 [0.95773967 0.23566857 0.09914585 0.15680593 0.07131737]
 [0.6293079  0.80348368 0.81140844 0.04561319 0.11062446]
 [0.02173531 0.42808424 0.83593944 0.48948866 0.51108173]
 [0.43934426 0.69892383 0.42682022 0.10947609 0.87788847]
 [0.25890557 0.79367771 0.6421139  0.19667346 0.59310318]
 [0.43216593 0.71561781 0.3418191  0.70499988 0.6149

## Bayesian Optimisation

In [2]:
# GP setup
kernel = (ConstantKernel(1.0, (1e-2, 1e2)) *
          Matern(length_scale=np.ones(d), nu=1.5) +
          WhiteKernel(noise_level=5e-3, noise_level_bounds=(1e-6, 1e-1)))

gp = GaussianProcessRegressor(kernel=kernel,
                              n_restarts_optimizer=8,
                              normalize_y=True,
                              random_state=42)
gp.fit(X, y)

# Sobol candidates in [0,1]^5
sob = Sobol(d=d, scramble=True, seed=None)
C = sob.random_base2(m=18)  

# GP predictions
mu, sigma = gp.predict(C, return_std=True)

# Expected Improvement (EI)
y_best = np.max(y)
xi = 0.01  
imp = mu - y_best - xi
Z = imp / sigma
ei = imp * norm.cdf(Z) + sigma * norm.pdf(Z)

# --- Pick next query ---
x_next = C[np.argmax(ei)]
print("Next point to query:",
      "-".join(f"{x:.6f}" for x in x_next))

Next point to query: 0.424677-0.367513-0.739997-0.813087-0.030487
