## Function Description
You’re tasked with optimising an ML model by tuning six hyperparameters, for example learning rate, regularisation strength or number of hidden layers. The function you’re maximising is the model’s performance score (such as accuracy or F1), but since the relationship between inputs and output isn’t known, it’s treated as a black-box function. The goal is to find the combination of hyperparameters that yields the highest possible performance.

## Load and Prepare Data

In [1]:
import numpy as np
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import Matern, WhiteKernel, ConstantKernel
from scipy.stats.qmc import Sobol
from scipy.stats import norm
import warnings
from sklearn.exceptions import ConvergenceWarning

warnings.filterwarnings(
    "ignore",
    category=ConvergenceWarning,
    module="sklearn"
)

# Load original dataset
X = np.load("../data/function_7/initial_inputs.npy")
y = np.load("../data/function_7/initial_outputs.npy")
d = X.shape[1] # dimension

print(f"original n: {len(X)}")
print()

# week 1 = initial

# week 2
x_new = np.array([[0.273438, 0.450690, 0.413488, 0.285023, 0.377760, 0.757027]])
y_new = np.array([1.883287428633328])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 3
x_new = np.array([[0.198552, 0.498391, 0.434876, 0.254163, 0.396552, 0.721236]])
y_new = np.array([2.038740881834282])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 4
x_new = np.array([[0.016750, 0.564445, 0.498901, 0.237872, 0.376071, 0.754913]])
y_new = np.array([1.4161998340106972])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 5
x_new = np.array([[0.202820, 0.354640, 0.005570, 0.266428, 0.373516, 0.013214]])
y_new = np.array([0.12749585379582876])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 6
x_new = np.array([[0.236909, 0.285530, 0.225819, 0.209358, 0.366238, 0.732886]])
y_new = np.array([2.328267059938682])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 7
x_new = np.array([[0.214572, 0.419397, 0.065811, 0.152936, 0.357296, 0.694855]])
y_new = np.array([1.5873114037650422])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 8
x_new = np.array([[0.296970, 0.175224, 0.967097, 0.217682,
                   0.381161, 0.806737]])
y_new = np.array([1.3151078392754891])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 9
x_new = np.array([[0.311930, 0.244347, 0.263703, 0.233867,
                   0.377674, 0.741498]])
y_new = np.array([2.4596082089588753])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 10
x_new = np.array([[0.346764, 0.117855, 0.122187, 0.232967,
                   0.342263, 0.711485]])
y_new = np.array([2.4637793179638843])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 11
x_new = np.array([[0.272196, 0.506051, 0.223097, 0.236510, 0.326314, 0.797848]])
y_new = np.array([1.578280104961618])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 12
x_new = np.array([[0.274485, 0.070371, 0.163388, 0.213310, 0.371978, 0.732172]])
y_new = np.array([2.356137319568785])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# week 13
x_new = np.array([[0.345007, 0.158281, 0.249855, 0.159331, 0.319883, 0.696840]])
y_new = np.array([2.4456844125131663])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

# final submission
x_new = np.array([[0.321126, 0.159640, 0.384855, 0.209467, 0.349849, 0.720931]])
y_new = np.array([2.8116569452461184])

X = np.vstack((X, x_new))
y = np.concatenate((y, y_new))

np.set_printoptions(suppress=True, precision=6)
print("X:\n", X)
print()
print("y:\n", y)
print()
print("n: ", len(y))
print()
idx_best = np.argmax(y)
print(f"current maximum:\nn: {idx_best+1}\ny: {y[idx_best]}\nX: {X[idx_best]}")

original n: 30

X:
 [[0.272624 0.324495 0.897109 0.832951 0.154063 0.795864]
 [0.543003 0.924694 0.341567 0.646486 0.71844  0.343133]
 [0.090832 0.661529 0.065931 0.258577 0.963453 0.640265]
 [0.118867 0.615055 0.905816 0.8553   0.413631 0.585236]
 [0.630218 0.838097 0.680013 0.731895 0.526737 0.348429]
 [0.764919 0.255883 0.609084 0.218079 0.322943 0.095794]
 [0.057896 0.491672 0.247422 0.218118 0.420428 0.73097 ]
 [0.195252 0.079227 0.55458  0.170567 0.014944 0.107032]
 [0.642303 0.836875 0.021793 0.101488 0.683071 0.692416]
 [0.789943 0.195545 0.575623 0.073659 0.259049 0.0511  ]
 [0.528497 0.457424 0.360096 0.362046 0.816891 0.637476]
 [0.722615 0.011813 0.063646 0.165173 0.079244 0.359952]
 [0.075665 0.334502 0.132733 0.608312 0.918386 0.822331]
 [0.942451 0.37744  0.486122 0.228791 0.082632 0.711958]
 [0.148647 0.033943 0.728806 0.316066 0.021769 0.516918]
 [0.817112 0.548168 0.103348 0.12437  0.728235 0.449674]
 [0.417626 0.0641   0.245669 0.559041 0.191531 0.254641]
 [0.726286 

## Bayesian Optimisation

In [2]:
# GP setup
kernel = (ConstantKernel(1.0, (1e-2, 1e2)) *
          Matern(length_scale=np.ones(d), nu=1.5) +
          WhiteKernel(noise_level=5e-3, noise_level_bounds=(1e-6, 1e-1)))

gp = GaussianProcessRegressor(kernel=kernel,
                              n_restarts_optimizer=8,
                              normalize_y=True,
                              random_state=42)
gp.fit(X, y)

# Sobol candidates in [0,1]^6
sob = Sobol(d=d, scramble=True, seed=None)
C = sob.random_base2(m=18) 

# GP predictions
mu, sigma = gp.predict(C, return_std=True)

# Expected Improvement (EI)
y_best = np.max(y)
xi = 0.01            
imp = mu - y_best - xi
Z = imp / sigma
ei = imp * norm.cdf(Z) + sigma * norm.pdf(Z)

# 6) Pick next query (already in [0,1]^6)
x_next = C[np.argmax(ei)]
print("Next point to query:",
      "-".join(f"{x:.6f}" for x in x_next))

Next point to query: 0.286768-0.053079-0.410542-0.093678-0.376177-0.661625
